server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/memo_auth_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: wkdwlsgh9622
    password: wlsgh1236
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
      jwt:
        host: localhost
        port: 6379
        password: wlsgh1236

jwt:
  secret: dmVyeWltcG9ydGFudHNlY3JldGNvZGUnfbewdkyWbbhdvbVBVDW
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds: 604800

  access-token-validity-ms: 3600000
  refresh-token-validity-ms: 1209600000

admin:
  email: k30ncuq9622
  password: wlsgh1236
